name: EC2 Scheduler

on:
  schedule:
    - cron: '0 14 * * *'  # 7 PM Pakistan Time (UTC+5) → 14:00 UTC
    - cron: '0 17 * * *'  # 10 PM Pakistan Time (UTC+5) → 17:00 UTC

  workflow_dispatch:  # Allows manual triggering

jobs:
  start-ec2:
    if: github.event.schedule == '0 14 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 Instance
        run: aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

  stop-ec2:
    if: github.event.schedule == '0 17 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 Instance
        run: aws ec2 stop-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

